### ISSUE TITLE
axes_reset ip  Does not restore access to address

### ISSUE THREAD

**Issue by razyr** [jazzband/django-axes#288]
When I run

```
manage.py axes_reset ip 123.123.123.123
```
Axes reports "1 attempts removed".

When I check, the related accessattempt object has been removed from the database as expected.  However, the IP remains blocked.   It seems to stay blocked until I restart the application docker container, at which point the address is able to connect again.

If I use Django admin to remove the related accessattempt object, the IP is immediately allowed to connect again.

This seems to be consistent and repeatable behaviour.

**Comment by aleksihakli** [comment]
Access uses the [`axes.utils.reset`](https://github.com/jazzband/django-axes/blob/da0c4b429a2065c562419b94342e0accdc64e104/axes/utils.py#L53) function for resetting the login attempts from the `manage` command and resets the cache with [`axes.attempts.get_cache_key`](https://github.com/jazzband/django-axes/blob/da0c4b429a2065c562419b94342e0accdc64e104/axes/attempts.py#L52) whereas the admin site just deletes the `AccessAttempt` objects related to the IP and the [`axes.signals.delete_cache_after_delete`](https://github.com/jazzband/django-axes/blob/da0c4b429a2065c562419b94342e0accdc64e104/axes/signals.py#L171) signal handler handles the deletion of cache keys.

@camilonova I think we should remove the extra deletion logic from the `axes.utils.reset` function since it already exists in `axes.signals.delete_cache_after_delete` signal handler, and investigate deeper into this potential bug.

There could be a flaw in the `AccessAttempt` reset / deletion code and it seems like we have duplicate deletion logic which fires on both deletion types, actually. There is a slight difference in the way the deletion is handled.

@razyr could you post your Docker container setup here as well, including your `Dockerfile` and `docker-compose` setups? Which cache backend and database are you using? Is this reproducible on dummy cache, in-memory cache, and Memcached / Redis cache backends?

**Comment by razyr** [comment]
This is a low traffic application, so we're just using the default in-memory cache.  The reported problem disappears with dummy (no) caching.

Our database is Postgres 9.4 as shown below in docker-compose.yml.   

Our dev Docker configuration is quite minimal with simply an application container and a database container.  We have a more sophisticated production.yml which adds an NGINX front end, but the issue reported here is consistent in both our dev and production environments with default caching.

Dockerfile
```
FROM python:3.6.3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install -r requirements.txt
```
docker-compose.yml
```
version: '2'
services:
  db:
    image: centos/postgresql-94-centos7:latest
    volumes:
      - ./db:/var/lib/pgsql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - FOOSECRET=BAR
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
    restart: always
    environment:
      - FOOSECRET=BAR
```
